<?php

/**
 * Implementation of hook_menu().
 */
function ding_pretix_menu() {
	$items = [];

	$items['admin/config/ding/pretix'] = array(
		'title' => 'Pretix settings',
		'description' => 'Settings and defaults for Pretix integration',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('ding_pretix_admin_settings_form'),
		'access arguments' => array('administer pretix settings'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'includes/ding_pretix.admin.inc',
	);

	return $items;
}