<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\dpl_pretix\EntityHelper;
use Drupal\dpl_pretix\FormHelper;
use Drupal\recurring_events\Entity\EventSeries;

/**
 * Implements hook_form_alter().
 */
function dpl_pretix_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  _dpl_pretix_form_helper()->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_entity_insert().
 */
function dpl_pretix_entity_insert(EntityInterface $entity): void {
  _dpl_pretix_entity_helper()->entityInsert($entity);
}

/**
 * Implements hook_entity_update().
 */
function dpl_pretix_entity_update(EntityInterface $entity): void {
  _dpl_pretix_entity_helper()->entityUpdate($entity);
}

/**
 * Implements hook_entity_delete().
 */
function dpl_pretix_entity_delete(EntityInterface $entity): void {
  _dpl_pretix_entity_helper()->entityDelete($entity);
}

/**
 * Implements hook_entity_prepare_form().
 */
function dpl_pretix_entity_prepare_form(EntityInterface $entity, string $operation, FormStateInterface $form_state): void {
  _dpl_pretix_form_helper()->prepareForm($entity, $operation, $form_state);
}

/**
 * Implements hook_recurring_events_event_instances_pre_create_alter().
 *
 * @param array<string, mixed> $events_to_create
 *    The events to create.
 * @param \Drupal\recurring_events\Entity\EventSeries $event
 *    The event.
 */
function dpl_pretix_recurring_events_event_instances_pre_create_alter(array $events_to_create, EventSeries $event): array {
  return _dpl_pretix_entity_helper()->recurringEventsEventInstancesPreCreateAlter($events_to_create, $event);
}

/**
 * Implements hook_recurring_events_save_pre_instances_deletion().
 *
 * @param \Drupal\recurring_events\Entity\EventSeries $event
 *   The event.
 */
function dpl_pretix_recurring_events_save_pre_instances_deletion(EventSeries $event): void {
  _dpl_pretix_entity_helper()->recurringEventsSavePreInstancesDeletion($event);
}

/**
 * Implements hook_recurring_events_save_post_instances_deletion().
 *
 * @param \Drupal\recurring_events\Entity\EventSeries $event
 *   The event.
 */
function dpl_pretix_recurring_events_save_post_instances_deletion(EventSeries $event): void {
  _dpl_pretix_entity_helper()->recurringEventsSavePostInstancesDeletion($event);
}

/**
 * Get form helper.
 */
function _dpl_pretix_form_helper(): FormHelper {
  return \Drupal::service(FormHelper::class);
}

/**
 * Get event helper.
 */
function _dpl_pretix_entity_helper(): EntityHelper {
  return \Drupal::service(EntityHelper::class);
}

// Local Variables:
// mode: php
// End:
