# https://taskfile.dev

version: '3'

tasks:
  dev:coding-standards:markdown:apply:
    desc: Apply Markdown coding standards
    cmds:
      - docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint --ignore LICENSE.md --ignore vendor/ '**/*.md' --dot --fix

  dev:coding-standards:markdown:check:
    desc: Apply and check Markdown coding standards
    cmds:
      - task: dev:coding-standards:markdown:apply
      - docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint --ignore LICENSE.md --ignore vendor/ '**/*.md' --dot

  dev:coding-standards:php:apply:
    desc: Apply PHP coding standards
    cmds:
      - task: dev:php
        vars:
          ARGS: vendor/bin/phpcbf

  dev:coding-standards:php:check:
    desc: Apply and check PHP coding standards
    cmds:
      - task: dev:coding-standards:php:apply
      - task: dev:php
        vars:
          ARGS: vendor/bin/phpcs

  dev:coding-standards:check:
    desc: Apply and check coding standards
    cmds:
      - task dev:coding-standards:markdown:apply
      - task dev:coding-standards:markdown:check
      - task dev:coding-standards:php:apply
      - task dev:coding-standards:php:check

  dev:code-analysis:
    desc: Analyse code
    cmds:
      - task: dev:php
        vars:
          ARGS: scripts/code-analysis

  dev:php:
    internal: true
    desc: Run php command
    cmds:
      - docker compose build
      - docker compose run --rm php composer install
      - docker compose run --rm --interactive --tty php {{.ARGS}}

  build:pretix-api-client:
    desc: Build customized version of https://github.com/itk-dev/pretix-api-client-php/
    cmds:
      - curl --silent --location https://github.com/itk-dev/pretix-api-client-php/archive/refs/tags/1.2.0.tar.gz > /tmp/pretix-api-client-php.tar.gz
      # Extract src folder from archive into src/Pretix
      - mkdir -p src/Pretix/ApiClient
      - tar xvf /tmp/pretix-api-client-php.tar.gz --directory=src/Pretix/ApiClient --strip-components=2 pretix-api-client-php-1.2.0/src
      # Change namespace
      - docker compose run --rm php sed --in-place 's@ItkDev\\Pretix\\Api@Drupal\\dpl_pretix\\Pretix\\ApiClient@' $(find src/Pretix/ApiClient -name '*.php')
      # Remove use of https://symfony.com/doc/current/components/options_resolver.html
      - patch --strip=1 < src/Pretix/ApiClient/patches/pretix-api-client.patch
      # Add missing functions
      - patch --strip=1 < src/Pretix/ApiClient/patches/pretix-api-client-functions.patch
