#!/usr/bin/env bash

script_dir=$PWD
module_name=dpl_pretix
drupal_dir=vendor/drupal-module-code-analysis
# Relative to $drupal_dir
module_path=web/sites/default/files/modules_local/$module_name

cd "$script_dir" || exit

drupal_composer() {
  composer --working-dir="$drupal_dir" --no-interaction "$@"
}

set -x

# Create new DPL CMS project
if [ ! -f "$drupal_dir/composer.json" ]; then
  rm -fr "$drupal_dir"
  # https://getcomposer.org/doc/03-cli.md#create-project
  composer --no-interaction create-project danskernesdigitalebibliotek/dpl-cms --repository='{"url": "https://github.com/danskernesdigitalebibliotek/dpl-cms", "type": "vcs"}' --add-repository "$drupal_dir"
fi

git -C "$drupal_dir" pull

# Copy our code into the modules folder

mkdir -p "$drupal_dir/$module_path"

# https://stackoverflow.com/a/15373763
rsync --archive --delete --compress . --filter=':- .gitignore' --exclude "$drupal_dir" --exclude .git "$drupal_dir/$module_path"

drupal_composer config minimum-stability dev

# Allow ALL plugins
# https://getcomposer.org/doc/06-config.md#allow-plugins
drupal_composer config --no-plugins allow-plugins true

drupal_composer require wikimedia/composer-merge-plugin
drupal_composer config extra.merge-plugin.include "$module_path/composer.json"
# https://www.drupal.org/project/drupal/issues/3220043#comment-14845434
drupal_composer require --dev symfony/phpunit-bridge

# Run PHPStan
(cd "$drupal_dir/$module_path" && "$script_dir/$drupal_dir/vendor/bin/phpstan" --configuration=phpstan.neon.dist -vvv --debug)
